export const CLASSES = {
    warrior: {
        label: 'Guerrier',
        description: '+2 dégâts corps à corps, agit 30% plus vite',
        hp: 50,
        maxHp: 50,
        mp: 12,
        maxMp: 12,
        meleeClassBonus: 2,
        mpRegen: 0,
        hpRegen: 0,
        gambler: false,
        cooldownMove: 2000,
        cooldownAttack: 3500,
    },
    tank: {
        label: 'Tank',
        description: '+15 PV, +5 dégâts corps à corps',
        hp: 65,
        maxHp: 65,
        mp: 12,
        maxMp: 12,
        meleeClassBonus: 5,
        mpRegen: 0,
        hpRegen: 0,
        gambler: false,
        cooldownMove: 3000,
        cooldownAttack: 5000,
    },
    mage: {
        label: 'Mage',
        description: '+6 MP, régénère 1 MP toutes les 5 secondes',
        hp: 50,
        maxHp: 50,
        mp: 18,
        maxMp: 18,
        meleeClassBonus: 0,
        mpRegen: 1,
        mpRegenInterval: 5000,
        hpRegen: 0,
        gambler: false,
        cooldownMove: 3000,
        cooldownAttack: 5000,
    },
    priest: {
        label: 'Prêtre',
        description: '+5 MP, régénère 2 HP toutes les 10 secondes',
        hp: 50,
        maxHp: 50,
        mp: 17,
        maxMp: 17,
        meleeClassBonus: 0,
        mpRegen: 0,
        hpRegen: 2,
        hpRegenInterval: 10000,
        gambler: false,
        cooldownMove: 3000,
        cooldownAttack: 5000,
    },
    gambler: {
        label: 'Parieur',
        description: '±5 HP ou ±3 MP toutes les 10 secondes',
        hp: 50,
        maxHp: 50,
        mp: 12,
        maxMp: 12,
        meleeClassBonus: 0,
        mpRegen: 5,
        hpRegen: 5,
        gambler: true,
        gamblerInterval: 10000,
        cooldownMove: 3000,
        cooldownAttack: 5000,
    }
}